#shell:
  #program: /bin

# use tmux to scroll you fkn idiot
scrolling:
  history: 0
font:
  size: 8 # laptop size
  #size: 12 # desktop size
  normal:
    family: "FiraCode Nerd Font"

import:
  - ~/.cache/wal/colors-alacritty.yml

window:
  opacity: .875
