#!/bin/bash

# num displays includes laptop display
NUM_DISPLAYS="$(xrandr -q | grep " connected" | wc -l)"
LAPTOP_DISPLAY="eDP-1"
# its eDP-1-1 for nvidia graphics
#LAPTOP_DISPLAY="eDP-1-1"
# for some reason the graphics mode changes the name of the displays
# on nvidia grpahics it is called HDMI-1
# on hybrid graphics it is called HDMI-1-0
# by default i boot into hybrid graphics so 1-0 is generally appropriate
CENTER_DISPLAY="HDMI-1-0"
# I never use 3 displays, but i have a feeling this will have to change if i do
RIGHT_DISPLAY="DP-1-0"

function one_display() {
	bspc monitor $LAPTOP_DISPLAY -d $LAPTOP_DISPLAY/1 $LAPTOP_DISPLAY/2 $LAPTOP_DISPLAY/3 $LAPTOP_DISPLAY/4 $LAPTOP_DISPLAY/5

    bspc rule -a lightcord desktop='^3'
}

function two_displays() {
	# assume that if two displays are connected then the external is connected through DP1 and is to the right
	xrandr --output $CENTER_DISPLAY --auto --right-of $LAPTOP_DISPLAY

	bspc monitor $CENTER_DISPLAY -d $CENTER_DISPLAY/1 $CENTER_DISPLAY/2 $CENTER_DISPLAY/3 $CENTER_DISPLAY/4 $CENTER_DISPLAY/5
	bspc monitor $LAPTOP_DISPLAY -d $LAPTOP_DISPLAY/6 $LAPTOP_DISPLAY/7 $LAPTOP_DISPLAY/8 $LAPTOP_DISPLAY/9 $LAPTOP_DISPLAY/10
}

function three_displays() {
	xrandr --output $CENTER_DISPLAY --auto --right-of $LAPTOP_DISPLAY
	xrandr --output $RIGHT_DISPLAY --auto --right-of $CENTER_DISPLAY --rotate right

	bspc monitor $CENTER_DISPLAY -d $CENTER_DISPLAY/1 $CENTER_DISPLAY/2 $CENTER_DISPLAY/3 $CENTER_DISPLAY/4
	bspc monitor $LAPTOP_DISPLAY -d $LAPTOP_DISPLAY/5 $LAPTOP_DISPLAY/6 $LAPTOP_DISPLAY/7 $LAPTOP_DISPLAY/8
	bspc monitor $RIGHT_DISPLAY -d $RIGHT_DISPLAY/9 $RIGHT_DISPLAY/10
}

case $NUM_DISPLAYS in
# laptop display left - horizantal monitor center
    "2")
        two_displays
        ;;
# laptop display left - horizantal monitor center - vertial monitor right
    "3")
        three_displays
        ;;
    *)
        # if the NUM_DISPLAYS is undetermined default to 1
        one_display
        sudo powertop --auto-tune
        ;;
esac

sxhkd &
setxkbmap -option ctrl:swapcaps
~/bin/wal_setter.sh $(head -n 1 ~/.config/wallpaper)
dunst &
picom --config ~/.config/picom/picom.conf &
unclutter &
polybar -c ~/.config/polybar/config.ini example &

bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

clipmenud &
