#!/bin/bash

feh --bg-scale ~/Pictures/wallpapers/anime/dragon_city.jpg

compton &
sxhkd &
dunst &

EXTERNAL_DISPLAY_NAME="DP-1"
LAPTOP_DISPLAY_NAME="eDP-1"

# the external display only works when the nvidia graphics card is turned on. 
# when nvidia graphics is on the LAPTOP_DISPLAY NAME changes
if [ $(optimus-manager --status | grep 'Current GPU mode : nvidia' | wc -l )  -eq '1' ]; then
	LAPTOP_DISPLAY_NAME="eDP-1-1"
elif [ $(optimus-manager --status | grep 'Current GPU mode : intel' | wc -l )  -eq '1' ]; then
	# if the intel card is in use then i should be saving battery. start powertop
	sudo powertop --auto-tune
fi

# Check if a monitor is conncted through DP1 (the adapter hdmi port)
if [ $(xrandr -q | grep " connected" | wc -l) -eq "2" ]; then
	# assume that if two displays are connected then the external is connected through DP1 and is to the right
	xrandr --output $EXTERNAL_DISPLAY_NAME --auto --right-of $LAPTOP_DISPLAY_NAME

	bspc monitor $EXTERNAL_DISPLAY_NAME -d $EXTERNAL_DISPLAY_NAME/1 $EXTERNAL_DISPLAY_NAME/2 $EXTERNAL_DISPLAY_NAME/3 $EXTERNAL_DISPLAY_NAME/4 $EXTERNAL_DISPLAY_NAME/5
	bspc monitor $LAPTOP_DISPLAY_NAME -d $LAPTOP_DISPLAY_NAME/6 $LAPTOP_DISPLAY_NAME/7 $LAPTOP_DISPLAY_NAME/8 $LAPTOP_DISPLAY_NAME/9 $EXTERNAL_DISPLAY_NAME/10
else
	bspc monitor $LAPTOP_DISPLAY_NAME -d $LAPTOP_DISPLAY_NAME/1 $LAPTOP_DISPLAY_NAME/2 $LAPTOP_DISPLAY_NAME/3 $LAPTOP_DISPLAY_NAME/4 $LAPTOP_DISPLAY_NAME/5
fi

~/.config/polybar/launch.sh &

bspc config border_width         2
bspc config window_gap          12


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
